- name: copy MongoDB Yum repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Server
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB listen address
  ansible.builtin.replace:
    path: /etc/mongodb.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start MongoDB
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes