- name: configure NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash



- name: app-prereq
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Install NodeJS dependencies
  community.general.npm:
    path: /app
    state: latest

- name: systemd setup
  ansible.builtin.include_tasks: "systemd.yml"



- name: load schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load